version: '3.9'

services:
  api:
    image: taskmanager
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '5000:80'
    env_file:
      - .env
  
  db:
    image: postgres
    ports:
      - '6000:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    depends_on:
      - minio
  

volumes:
  postgres-data: